### ISSUE TITLE
Use of unresolved identifier 'Mattress'

### ISSUE THREAD

**Issue by aetsyss** [buzzfeed/mattress#24]
Hi,
after installation via cocoa pods this line
let urlCache = Mattress.URLCache(memoryCapacity: 20 * MB, diskCapacity: 20 * MB, diskPath: nil,
            mattressDiskCapacity: 1 * GB, mattressDiskPath: nil, mattressSearchPathDirectory: .DocumentDirectory,
            isOfflineHandler: isOfflineHandler)

shows an error Use of unresolved identifier 'Mattress'

**Comment by sey** [comment]
I think you forgot to import the module on top of the file.
```swift
import Mattress
```

**Comment by aetsyss** [comment]
Thanks a lot! This helped me!
