### ISSUE TITLE
Plans to support Objective C Projects

### ISSUE THREAD

**Issue by ogezue** [buzzfeed/mattress#25]
Hi - i currently have a big Objective C Project that will not be migrated to Swift. It has been migrated to iOS9 as minimum deployment target.

Now I imported Mattress via cocoapods and and added the use_frameworks! tag. This causes problems with other imported libraries.

Have you planned to implement support for Objective C that is compatible to other library? 
Another point is that I get a warning regarding deprecation of NSURLConnection in your lib with iOS9.

**Comment by lordkev** [comment]
Hi @ogezue,

Can you give some specifics on the problems with other imported libraries that you're seeing? Do you mean issues related to use_frameworks in CocoaPods? I know that some libraries out there still don't support this. Unfortunately, the only way to bring in Swift projects via CocoaPods is as a framework.

My suggestion would be to use Carthage to bring in any Swift frameworks. On our older Objective-C project we've taken a split approach continuing to use CocoaPods (without use_frameworks!) to bring in any legacy libraries, and Carthage to bring in any new Swift frameworks. It's a bit of a pain, but has worked out well for us so far.

I'll take a look at the deprecation warning.

**Comment by ogezue** [comment]
Hi lordkev,
thanks for your answer! I will try it with Carthage. If you need an example, try to integrate RestKit and Mattress in one project.

**Comment by lordkev** [comment]
Hi @ogezue,

As for the CocoaPods issue, what version of RestKit are you using? Mattress requires building with the use_frameworks! option. It looks like support for this was just added in RestKit in August, so you would need to be using at least 0.25.0 for this to work. Unfortunately, there's nothing that can be done on the Mattress side for this...these other libraries will need to support being built as a framework.

If you're able to provide the error message you're receiving in Carthage it would be very helpful. I just attempted with the command `carthage update --platform ios` and it built without issue for me.

Integrating into an Obj-C project should be no different aside from the import statement used. Would having example code in Obj-C be helpful?

**Comment by ogezue** [comment]
Currently I'm rewriting my app in Swift, so this ticket isn't relevant for me anymore. The RK version that I was using is the latest.

In my eyes you could close the ticket.

**Comment by lordkev** [comment]
Great, thanks!
