### ISSUE TITLE
stuff not nil

### ISSUE THREAD

**Issue by ogezue** [buzzfeed/mattress#27]
When I add mattress to my project with alamofire and objectmapper this method in mattress says "stuff not nil"

```Swift
func diskPathForRequest(request: NSURLRequest) -> NSURL? {
        var url: NSURL?
        if let
            hash = hashForRequest(request),
            baseURL = diskPath()
        {
            NSLog("stuff not nil")
            url = NSURL(string: hash, relativeToURL: baseURL)
        }
        return url
    }
```

Is there something I have to configure?

**Comment by lordkev** [comment]
Sorry, this was a debugging log statement accidentally left in. It means it's working as intended. Removing this now. :)
