### ISSUE TITLE
Example-Project does not build

### ISSUE THREAD

**Issue by ogezue** [buzzfeed/mattress#30]
(null): error: /Users/kevinlord/Library/Developer/Xcode/DerivedData/Mattress-aqemttuzbkdmvefylygnstriakjp/Build/Products/Debug-iphoneos/CommonCrypto.framework: No such file or directory

(null): error: /Users/kevinlord/Library/Developer/Xcode/DerivedData/Mattress-aqemttuzbkdmvefylygnstriakjp/Build/Products/Debug-iphoneos/Mattress.framework: No such file or directory

Seems the project has a dependency to kevins mac ;)

**Comment by lordkev** [comment]
Fixed by PR ^^
